### ISSUE TITLE
Insufficient "layer" configuration parameter

### ISSUE THREAD

**Issue by jusabatier** [sigrennesmetropole/geor_urbanisme_mapstore#13]
What is the 'layer' parameter ?

As I see using the addon, it's the PCI layer to show when using the addon. Is it right ?

I let the default value 'urbanisme_parcelle' and it request on : 

https://geoportail.lepuyenvelay.fr/geoserver/gwc/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=urbanisme_parcelle&tileMatrixSet=EPSG:4326&expandLimit=10

So it automatically request on the Geoserver's WMTS of the Georchestra's instance.

Here we use a standalone GeoWebCache, so the layer URL is : 

https://geoportail.lepuyenvelay.fr/geowebcache/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=pci:cadastre&tileMatrixSet=EPSG:4326&expandLimit=10

After that, it use same layer's WMS to retrieve the clicked parcel.
I think this have to be two distinct config like in cadastrapp.

One for the display layer which load a WMTS layer at plugin's openning
A second for querying clicked parcels over WMS.

**Comment by tdipisa** [comment]
@jusabatier thank you for reporting. I will ask developers to check if the readme documentation is properly updated.

**Comment by offtherailz** [comment]
About the documentation, it seems to be correct: 

The original application had the same [layer](https://github.com/sigrennesmetropole/addon_urbanisme/blob/a2c1c27117940093640accb8e3d750a3cf8d2d60/src/addon/urbanisme/config.json#L7) configured. 

It's under "cadastre.layer" in the original json but it is a unique layer so it has been called simply `layer` in this version. 
The only difference seems to be the layer `service` that is automatically get from `cadastrapp` `cadastreWMSURL`,instead of having to configure it in the json in this new version.
If this causes problem, I can change it and make it configurable explicitly, and use `cadastreWMSURL` by default.

Here the doc:
https://github.com/sigrennesmetropole/geor_urbanisme_mapstore#plugin-configuration

Note that "Plu" layer configuration is not used in the original app. The only trace I've found is in this commented code. https://github.com/sigrennesmetropole/addon_urbanisme/blob/fb3a3e0e701c93d74cb7c29137d77f9e5a392a7f/src/addon/urbanisme/js/main.js#L353
